jobs:
  build:
    name: Compile
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - continue-on-error: true
      name: Test with JUnit
      run: ant -noinput -buildfile build.xml test
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - '11'
        - '17'
        - '19'
name: Build (pull request)
on:
  repository_dispatch:
    types: trigger-ga___ant-pull.yml
