jobs:
  build:
    name: Compile
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - continue-on-error: true
      name: Test with JUnit
      run: ant -noinput -buildfile build.xml test
    - continue-on-error: true
      name: Test with JUnit
      run: ant -noinput -buildfile build.xml report
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - '11'
        - '17'
        - '19'
name: Build
on:
  repository_dispatch:
    types: trigger-ga___ant.yml
